#!/bin/bash
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/bspwm/polybar/colors.ini
include-file = ~/.config/bspwm/polybar/modules.ini
include-file = ~/.config/bspwm/polybar/decor.ini
include-file = ~/.config/bspwm/polybar/system

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/bar]
monitor =
monitor-fallback =
monitor-strict = false

override-redirect = false

bottom = false
fixed-center = true

width = 100%
height = 25

offset-x = 0%
offset-y = 0%

background = ${color.background}
foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 2
line-color = ${color.blue}

# border-top-size = 1
# border-bottom-size = 2
border-color = ${color.background}

padding = 0

module-margin-left = 0
module-margin-right = 0

wm-restack = bspwm

# font-0 = "Source Code Pro Medium:size=10;3"
font-0 = "Montserrat:weight=SemiBold:size=10;2"
font-1 = "Iosevka Nerd Font:size=11;3"
font-2 = "Iosevka Nerd Font:size=16;4"
font-3 = "Iosevka Nerd Font:size=18;4"
font-4 = "Source Code Pro Bold:size=13;3"
# font-1 = Hack Nerd Font:size=11;2

# Default
modules-left = bspwm sep spacing mod 
modules-center = date time 
modules-right = network spacing sep spacing battery spacing volume spacing memory sep

spacing = 0
dim-value = 1.0

tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 5
tray-scale = 1.0

enable-ipc = true

cursor-click = 
cursor-scroll = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]
throttle-output = 5
throttle-output-for = 10

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
