#!/bin/bash
# Basic Settings
# set hidden true
set ignorecase true
set icons true
set drawbox true

cmd open &xdg-open $f

# Custom Functions
cmd mkdir ${{
  printf "Directory Name: "
  read ans
  mkdir $ans
}}

cmd mkfile ${{
  printf "File Name: "
  read ans
  $EDITOR $ans
}}

# cmd setwallpaper ${{
#   cp $f ~/.config/wall.jpg
#   nohup hyprpaper & > /dev/null
# }}

cmd setwallpaper %cp "$f" ~/.config/wall.jpg && xwallpaper --zoom "$f"

# Archive bindings
cmd unarchive ${{
  case "$f" in
      *.zip) unzip "$f" ;;
      *.tar.gz) tar -xzvf "$f" ;;
      *.tar.bz2) tar -xjvf "$f" ;;
      *.tar) tar -xvf "$f" ;;
      *) echo "Unsupported format" ;;
  esac
}}

# Execute exe
cmd execute ${{
	wine "$f"
}}

# Trash bindings
cmd trash ${{
  files=$(printf "$fx" | tr '\n' ';')
  while [ "$files" ]; do
    file=${files%%;*}

    trash-put "$(basename "$file")"
    if [ "$files" = "$file" ]; then
      files=''
    else
      files="${files#*;}"
    fi
  done
}}

cmd restore_trash ${{
  trash-restore
}}

# Bindings
# Remove some defaults
map m
map o
map n
map "'"
map '"'
map d

map c $code "$f"

map au unarchive
map ae execute

# Basic Functions
map . set hidden!
map DD delete
map p paste
map xx cut
map yy copy
map <enter> open
map R reload
map mf mkfile
map md mkdir
map bg setwallpaper
map C clear

map dd trash
map dr restore_trash

# Movement
map gd cd ~/Dev
map gD cd ~/Downloads
map gp cd ~/Pictures
map gc cd ~/.config
map gb cd ~/.local/bin
map gr cd ~/Repos
