#!/bin/sh

#	          _     _       _          
#	 _____  _| |__ | | ____| |_ __ ___
#	/ __\ \/ / '_ \| |/ / _` | '__/ __|
#	\__ \>  <| | | |   < (_| | | | (__
#	|___/_/\_\_| |_|_|\_\__,_|_|  \___|


# reloads sxhkd configuration:
super + Escape
    pkill -USR1 -x sxhkd

# Lock Screen
super + p; l
    i3lock-fancy && systemctl suspend

# Launch Applications using keychords
super + a; {f,c,m,v,s,w,n,e,i,p}
    {nautilus,code,bluemail,virt-manager,spotify,$BROWSER, notion-app-enhanced, emacs,idea,postman}

# Launch web-apps
super + w; {w,e}
    {whatsapp, excalidraw}

# Launch Utilities
super + p; {p}
    {pavucontrol}
